name: mydat
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - conda-libmamba-solver
  - jupyterlab
  - ipywidgets
  - ipykernel
  - nodejs
  - numpy
  - scipy
  - pandas
  - openpyxl
  - types-openpyxl
  - matplotlib
  - seaborn
  - types-seaborn
  - statsmodels
  - tqdm
  - types-tqdm
  - pyarrow
  - fastparquet
  - polars
  - xlsx2csv
  - xlsxwriter
  - cairosvg
  - pynvim
  - pyperclip
  - jupytext
  - python-dotenv
  - fastapi
  - orjson
  - types-orjson
  - python-multipart
  - plotly::plotly
  - altair-all
  - vega_datasets
  - fiona
  - geopandas
  - pip:
      - catppuccin
      - catppuccin[pygments]
