[project]
authors = ["Rabeez Riaz <ruoter123@gmail.com>"]
channels = ["conda-forge", "plotly"]
description = "Add a short description here"
name = "mydat"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
app = "uvicorn app.main:application --port 6969 --reload --reload-dir \"./app\""

[dependencies]
python = ">=3.13.1,<3.14"
pip = ">=24.3.1,<25"
polars = ">=1.17.1,<2"
python-dotenv = ">=1.0.1,<2"
colorama = ">=0.4.6,<0.5"
fastapi = ">=0.115.6,<0.116"
orjson = ">=3.10.15,<4"
types-orjson = ">=3.6.2,<4"
python-multipart = ">=0.0.20,<0.0.21"
plotly = { version = ">=5.24.1,<6", channel = "plotly" }
pandas = ">=2.2.3,<3"
alembic = ">=1.14.0,<2"
sqlalchemy = ">=2.0.37,<3"
networkx = ">=3.4.2,<4"

[pypi-dependencies]
catppuccin = { version = ">=2.3.4, <3", extras = ["pygments"] }
jinja2-fragments = ">=1.7.0, <2"

[feature.dev.dependencies]
vega_datasets = ">=0.9.0,<0.10"

[feature.nvim.dependencies]
pynvim = "*"
pyperclip = "*"
jupytext = "*"
jupyter = "*"

[feature.nvim.tasks]
nvim = "nvim"

[environments]
dev = ["dev"]
nvim = ["dev", "nvim"]
